name:  Continuous Deployment

on:
  push:
    branches: [ develop ]
    # paths:
    #   - 'src/*'
    #   - 'test/*'

jobs:

  build:

    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Local Feed
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

    - name: Build
      run: | 
        dotnet remove ${{ github.workspace }}\src\Unity.Container.csproj reference "..\..\Abstractions\src\Unity.Abstractions.csproj"
        dotnet add src\Unity.Container.csproj package Unity.Abstractions --version *-*
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True tests

    - name: Test
      run: | 
        dotnet test tests

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
