name:  Continuous Deployment

on:
  push:
    branches: [ develop ]
    # paths:
    #   - 'src/*'
    #   - 'test/*'

jobs:

  build:

    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'
      LocalSource: ${{ github.workspace }}/packages

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
        nuget-version: '5.6'

    - name: Install Abstractions
      run: |
        nuget install Unity.Abstractions -Prerelease -ExcludeVersion -OutputDirectory ${{ env.LocalSource }}

    - name: Build
      run: | 
        dotnet remove ${{ github.workspace }}\src\Unity.Container.csproj reference "..\..\Abstractions\src\Unity.Abstractions.csproj"
        dotnet add ${{ github.workspace }}\src\Unity.Container.csproj package --source ${{ env.LocalSource }} Unity.Abstractions
              
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True tests

    - name: Test
      run: | 
        dotnet test tests

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
