name:  Continuous Deployment

on:
  push:
    branches: [ develop ]
    # paths:
    #   - 'src/*'
    #   - 'test/*'

jobs:

  build:

    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
        nuget-version: '5.6'

    - name: Restore
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        nuget restore src\Unity.Container.csproj
        nuget restore src\Unity.Container.csproj

    - name: Build
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:False src
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:False tests

    - name: Test
      run: | 
        dotnet test tests

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
